---
# model_name
# bert_wt
# bert_squad, bert_qa
# bert_passage
# bert_base
# bert_rr
# bert_ada
# marge
model_name: 'bert_rr'

mode: 'train'

# marge: 2005, 2006, 2007, tdqfs, eli5-test
# lqsum: wikiref_test, debatepedia_test
# wikicat_company, wikicat_animal, wikicat_film
# ducdoc_2005, ducdoc_2006, ducdoc_2007
# duccluster_2005, duccluster_2006, duccluster_2007
# tdqfsdoc, tdqfscluster
test_year: 'debatepedia_all'

debug: null  # True, null

auto_parallel: True

word_tokenizer: 'bert'  # bert, nltk
preload_model_tokenizer: True  # True when using pre-trained Bert model: None, qa, rr
# vocab: 'bert'  # bert

grain: 'sent'
